//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Comprend = new HashSet<Comprend>();
            this.Contient = new HashSet<Contient>();
            this.Vend = new HashSet<Vend>();
            this.Sous_Rubrique = new HashSet<Sous_Rubrique>();
        }
    
        public int ID_Article { get; set; }
        public string Nom_Article { get; set; }
        public string Marque_Article { get; set; }
        public string Libelle_Court { get; set; }
        public string Description { get; set; }
        public int Reference_Fournisseur { get; set; }
        public decimal Prix_Vente_HT { get; set; }
        public byte[] Image_Article { get; set; }
        public Nullable<int> Stock_Article { get; set; }
        public decimal Prix_Achat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprend> Comprend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contient> Contient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vend> Vend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sous_Rubrique> Sous_Rubrique { get; set; }
    }
}
