//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Commande = new HashSet<Commande>();
            this.Delivre = new HashSet<Delivre>();
            this.Commercial = new HashSet<Commercial>();
        }
    
        public int ID_Client { get; set; }
        public Nullable<bool> Particulier_Professionnel { get; set; }
        public string Nom_Particulier { get; set; }
        public string Prenom_Particulier { get; set; }
        public string Nom_Enseigne { get; set; }
        public Nullable<double> No_Siret { get; set; }
        public string Adresse_Facturation { get; set; }
        public string Code_Postal_Facturation { get; set; }
        public string Ville_Facturation { get; set; }
        public string Adresse_Livraison { get; set; }
        public string Code_Postal_Livraison { get; set; }
        public string Ville_Livraison { get; set; }
        public string No_Telephone_Client { get; set; }
        public string No_Fax_Client { get; set; }
        public string Mail_Client { get; set; }
        public string Condition_Reglement_Particulier { get; set; }
        public string Condition_Reglement_Professionel { get; set; }
        public Nullable<int> Remise { get; set; }
        public Nullable<int> Coefficient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commande { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivre> Delivre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commercial> Commercial { get; set; }
    }
}
