//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.Contient = new HashSet<Contient>();
            this.Livraison = new HashSet<Livraison>();
        }
    
        public int ID_Commande { get; set; }
        public decimal Montant_a_regler { get; set; }
        public System.DateTime Date_De_Facturation { get; set; }
        public string Mode_De_Paiement { get; set; }
        public decimal Montant_HT { get; set; }
        public System.DateTime Date_Reglement { get; set; }
        public decimal Montant_Regle { get; set; }
        public int TVA { get; set; }
        public System.DateTime Date_Commande { get; set; }
        public int ID_Client { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contient> Contient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livraison> Livraison { get; set; }
    }
}
