//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprend
    {
        public Nullable<int> Quantite_Livre { get; set; }
        public int ID_Article { get; set; }
        public int ID_Bon_Livraison { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Livraison Livraison { get; set; }
    }
}
