//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contient
    {
        public int Quantite_Article { get; set; }
        public decimal Prix_De_Vente_HT { get; set; }
        public int ID_Commande { get; set; }
        public int ID_Article { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Article Article { get; set; }
    }
}
