//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vend
    {
        public int Quantite_Fournisseur { get; set; }
        public int No_Bon_Livraison { get; set; }
        public Nullable<System.DateTime> Date_Livraison { get; set; }
        public decimal Prix_Achat_Fournisseur { get; set; }
        public int ID_Fournisseur { get; set; }
        public int ID_Article { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
    }
}
